# Generated by Django 5.0 on 2023-12-24 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_profile_info',
            old_name='porfolio_site',
            new_name='portfolio_site',
        ),
    ]
